doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            article_id: App\Blog\Post\Domain\OrmType\ArticleIdType
            comment_id: App\Blog\Post\Domain\OrmType\CommentIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Post:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Blog/Post/Infrastructure/DoctrineMapping'
                prefix: 'App\Blog\Post\Domain\Entity'
                alias: Blog
            User:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Blog/User/Infrastructure/DoctrineMapping'
                prefix: 'App\Blog\User\Domain\Entity'
                alias: User
